name: Build, Analyze, Test and Deploy
on:
  push:
    branches:
    - 'master'
    - 'release/**'
    - 'hotfix/**'
    - '!dev'
    - '!feature/**'
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.7.8+hotfix.4'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Release APK base a tag created manualy
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/debug/*.apk"
            token: ${{ secrets.github_access_token }}